/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package anagram_kotlin

import org.junit.Test
import org.junit.Assert

class AppTest {
    @Test fun isTrue() {
        Assert.assertTrue(true);
    }
}
